-- SQL for Supabase: create table, sample data, function and RLS

-- 1) Create table
create table if not exists public.gifts (
  id bigint generated by default as identity primary key,
  title text not null,
  reserved_by text,
  created_at timestamptz default now()
);

-- 2) Sample items (edit or remove)
insert into public.gifts (title) values
('Dárkový koš'),
('Kniha: Programování pro začátečníky'),
('Dárkový poukaz 1000 Kč'),
('Hrnek s potiskem');

-- 3) Function for atomic reservation (security definer)
create or replace function public.reserve_gift(p_gift_id bigint, p_name text)
returns table(id bigint, title text, reserved_by text) language plpgsql security definer as $$
begin
  update public.gifts set reserved_by = p_name where id = p_gift_id and reserved_by is null;
  return query select id, title, reserved_by from public.gifts where id = p_gift_id;
end; $$;

-- 4) Grant execute on the function to anon role so frontend can call it
grant execute on function public.reserve_gift(bigint, text) to anon;

-- 5) Enable RLS and allow public select (so everyone can see list)
alter table public.gifts enable row level security;
create policy select_gifts on public.gifts for select using (true);

-- 6) Prevent direct updates by anon (only function should modify rows)
create policy no_direct_update on public.gifts for update using (false);

-- After running this SQL in Supabase SQL editor the frontend can call rpc('reserve_gift', ...).
